#  -*-coding:utf-8-*-
# python2.7
# 庄建伟

In [26]:
# -*-coding:utf-8-*-
import numpy as np
import pandas as pd
import string

In [27]:
list1 = []
list2 = [chr(i) for i in range(65,91)]
list3 = ['one','two','three','four']
list4 = list(string.ascii_lowercase)   ########26个字母

In [28]:
x = np.random.binomial(1,0.5,[26,4])   #生成了26*4服从二项分布的数组
print x

[[0 0 1 1]
 [0 1 1 0]
 [0 0 1 1]
 [1 0 0 0]
 [1 1 1 0]
 [0 0 1 0]
 [1 1 1 1]
 [1 0 1 0]
 [0 1 1 1]
 [0 0 1 0]
 [0 0 0 1]
 [0 1 0 0]
 [0 1 1 1]
 [0 1 0 0]
 [1 0 0 0]
 [0 1 1 0]
 [0 0 0 1]
 [0 0 1 1]
 [1 1 0 1]
 [1 1 0 0]
 [1 1 1 1]
 [0 1 1 1]
 [1 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [1 0 0 1]]


In [29]:
for i,j in enumerate(x):      #从数组中选出大于0.5的数据
    for k in x[i]:
        if k > 0.5:
            list1.append(k)
print list1

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [30]:
frame = pd.DataFrame(x,list2,list3)   #生成行索引为26个字母，列索引为'one','two','three','four'的dataframe
print frame
print frame['two']  #'= frame[[1]]，取出‘1’列的方法'

   one  two  three  four
A    0    0      1     1
B    0    1      1     0
C    0    0      1     1
D    1    0      0     0
E    1    1      1     0
F    0    0      1     0
G    1    1      1     1
H    1    0      1     0
I    0    1      1     1
J    0    0      1     0
K    0    0      0     1
L    0    1      0     0
M    0    1      1     1
N    0    1      0     0
O    1    0      0     0
P    0    1      1     0
Q    0    0      0     1
R    0    0      1     1
S    1    1      0     1
T    1    1      0     0
U    1    1      1     1
V    0    1      1     1
W    1    0      1     0
X    0    0      1     0
Y    0    0      1     0
Z    1    0      0     1
A    0
B    1
C    0
D    0
E    1
F    0
G    1
H    0
I    1
J    0
K    0
L    1
M    1
N    1
O    0
P    1
Q    0
R    0
S    1
T    1
U    1
V    1
W    0
X    0
Y    0
Z    0
Name: two, dtype: int64


In [31]:
print frame.sort_values('two',ascending=False).head(5)  #取出‘two’列排序前五的行

   one  two  three  four
N    0    1      0     0
E    1    1      1     0
G    1    1      1     1
V    0    1      1     1
I    0    1      1     1


In [25]:
#计算‘one’列           等价的做法：# from numpy import sum,median,var
print np.sum(frame['one'])         # = print sum(frame['one'])
print np.median(frame['one'])      # = print median(frame['one'])
print np.var(frame['one'])         # = print var(frame['one'])

#print frame[frame.two>1]#保留dataframe中符合，two>1的数据。

13
0.5
0.25
